### ISSUE TITLE
"Quote all fields" formats should be preserved

### ISSUE THREAD

**Issue by atruskie** [ODIQueensland/data-curator#853] opened 2018-10-16 22:47 UTC
It's important to preserve the formatting of the document as it was ingested. We don't always have creation control of documents and mass changes for documents in soruce control systems is bad practice.

### Current Behaviour (for problems)

Currently, data-curator strips all quotes from all fields.

### Expected Behaviour

If all fields are quoted, the the document when saved should have all fields quoted. To put it another way, my git diff should only include the lines that have changed.

### Steps to Reproduce

1. Open Data Curator using the icon
2. Open a CSV file that has all fields quoted
3. Make any change
4. Save the file
5. `git diff` the file and note that all lines were modified and all quotes were stripped

### Your Environment

* Data Curator version: 1.0.0
* Operating System and version: Windows 10 version 1803

---
One line was changed...

![image](https://user-images.githubusercontent.com/1452968/47051759-f3574200-d1e8-11e8-87b8-c189f9ee60ac.png)

**Comment by mattRedBox** [comment] 2018-10-19 01:51
Hi @atruskie 
Yes I can replicate this behaviour - while we do have underlying libs we rely on for default csv dialect, this seems to be happening on open (quotes disappear as soon as I open a 'quoted' csv file).
I'll look into this - thanks for raising.

**Comment by mattRedBox** [comment] 2019-05-31 03:06
Hi @atruskie
@markwheels 
This one's a little tricky as I need to make sure it's not affected by the csv dialect settings that are part of the [frictionless spec](https://frictionlessdata.io/specs/csv-dialect/)
I also need to make sure that that nothing else changes the output when export/import occurs.
If I have to add back quotes, similar to adding back BOM #847, I'll need to test whether this will adversely affect performance for large files. 
I'm presuming @atruskie that the desired behaviour isn't to see quotes now appear in the Data-Curator cells, but only to ensure they are still there on writing back to file.
I think that part of the issue is that for importing csv files, quotes are by default used simply to pick where field boundaries are, before Data-Curator converts it to arrays of rows which are then arrays of strings (which of course have quotes). Nothing is marking or holding that the original data itself had quotes. I'll need a little more time on this one, @markwheels compared to other prelims marked before today as I haven't quite figured out what is specifically losing the quotes and because the solution may not be as simple as the flagging and re-adding (as potential performance issue mentioned above) - so marking this as longer than the others for effort.

**Comment by atruskie** [comment] 2019-06-03 02:45
> I'm presuming @atruskie that the desired behaviour isn't to see quotes now appear in the Data-Curator cells, but only to ensure they are still there on writing back to file.

Yes, that is correct. This really boils down to: If I change one cell, I want to see one line changed in my git diff.

If there is some kind of data specification (like a frictionless spec), then it would be great to apply it. In this case, there was no spec.

> Nothing is marking or holding that the original data itself had quotes.

Yes, I can imagine that is the problem. I wonder, can you infer a style (or a frictionless spec - I don't know how they work but they seem compatible) from a file when it is opened?

**Closed** 2019-06-06 22:41 UTC
Labels: est:Moderate, est:Score=7, fn:Open-Data, problem:Bug, support, support:Approved
